sudo: false
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install pylint>=1.8.2 mypy>=0.560
script:
  - pylint pydreamscreen
  - mypy pydreamscreen